version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: pg14
    restart: always
    environment:
      POSTGRES_USER: dbtesting
      POSTGRES_PASSWORD: dbtesting
      POSTGRES_DB: klontong
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
